:uri-distribution-issues: https://github.com/transpower-nz/open-scd/issues

= SCL Editor - Transpower's OpenSCD Core Distribution

The SCL editor is a light weight editor for substation configuration language as defined in the IEC 61850-6.
This editor is been created with a focus on a general user that does want to be close to the process described in the standard and an easy to maintain distribution (for long term stability).

Give it a try on https://transpower-nz.github.io/open-scd

== Scope

It is not the goal to reach every user of SCL, nor is it the goal to support all history of the standard. Out of scope is for example:

- Edition 1 of the IEC 61850-6
- Support of multi-edition projects

CAUTION: This distribution is in development and must be used with care!
If you found a bug please share with us and write an {uri-distribution-issues}[issue].

== Security

We do NOT upload any information of any sort.
You browser is only downloading never uploading anything.
So when you connect to [SCL editor](https://transpower-nz.github.io/open-scd) you download/update all the JavaScript files to run the editor in your browser.
That is why you can work offline one you have connected to the page once!


== Adding a plugin

Add the submodule pointing toward the published bundle:

  git submodule add -b gh-pages https://github.com/OpenEnergyTools/scl-ied-editor plugins/scl-ied-editor

Add to the `plugins.json`:

[source,json]
----
    {
      "name": "IED editor",
      "icon": "developer_board",
      "active": true,
      "requireDoc": true,
      "src": "plugins/scl-ied-editor/scl-ied-editor.js"
    }
----

TIP: Ensure there are commas between plugins but no trailing commas.

== Installing a release

Three difference releases are provided for each release:

* an msi file for Windows users (install with e.g. `msiexec /i openscd-transpower_win_x64_0.1.0_latest.msi`)
* an NSIS installer (run the installer e.g. `openscd-transpower_win_x64_0.1.0_latest_nsis.exe`)
* a stand-alone executable (run the executable on x64 machines, e.g. `openscd-transpower_win_x64_0.1.0_latest.exe`)

Code signing is not provided.