import { LitElement, TemplateResult, PropertyValues } from 'lit';
import '@material/mwc-icon-button';
import '@material/mwc-icon-button-toggle';
import '@material/mwc-textfield';
import { Point } from './foundation/sldUtil.js';
import { IED, Connection } from './foundation/types.js';
import '@scopedelement/material-web/checkbox/checkbox.js';
import '@scopedelement/material-web/list/list.js';
import '@scopedelement/material-web/list/list-item.js';
import '@scopedelement/material-web/button/text-button.js';
import '@scopedelement/material-web/fab/fab.js';
import '@scopedelement/material-web/icon/icon.js';
declare const CommunicationMappingEditor_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class CommunicationMappingEditor extends CommunicationMappingEditor_base {
    static scopedElements: {
        'mwc-textfield': CustomElementConstructor | undefined;
        'mwc-icon-button': CustomElementConstructor | undefined;
        'mwc-icon-button-toggle': CustomElementConstructor | undefined;
        'md-list': CustomElementConstructor | undefined;
        'md-list-item': CustomElementConstructor | undefined;
        'md-checkbox': CustomElementConstructor | undefined;
        'md-text-button': CustomElementConstructor | undefined;
        'md-fab': CustomElementConstructor | undefined;
        'md-icon': CustomElementConstructor | undefined;
    };
    substation: Element;
    gridSize: number;
    connections: Connection[];
    private ieds;
    private computeIeds;
    filterReport: boolean;
    filterGOOSE: boolean;
    filterSMV: boolean;
    selectedIed?: Element;
    filterRcv: boolean;
    filterSend: boolean;
    sourceIEDFilter: string;
    targetIEDFilter: string;
    cbNameFilter: string;
    vlanFilter: string;
    priorityFilter: string;
    selectedVlans: string[];
    selectedPriorities: string[];
    showFilterBox: boolean;
    showVlanDropdown: boolean;
    showPriorityDropdown: boolean;
    showManufacturerDropdown: boolean;
    manufacturerValues: string[];
    typeValues: string[];
    manufacturerTypeMap: Record<string, string[]>;
    selectedManufacturers: string[];
    selectedTypes: string[];
    editMode: boolean;
    showLabel: boolean;
    placing?: Element;
    placingLabel?: Element;
    placingOffset: Point;
    vlanValues: string[];
    priorityValues: string[];
    mouseX: number;
    mouseY: number;
    mouseX2: number;
    mouseY2: number;
    linkedEquipments: Element[];
    get idle(): boolean;
    sld: SVGGraphicsElement;
    container: HTMLDivElement;
    constructor();
    svgCoordinates(clientX: number, clientY: number): Point;
    handleKeydown: ({ key }: KeyboardEvent) => void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    reset(): void;
    placeLabel(element: Element, x: number, y: number): void;
    startPlacingLabel(element: Element | undefined, offset?: Point): void;
    placeElement(element: Element, x: number, y: number): void;
    startPlacing(element: Element | undefined, offset?: Point): void;
    private get isPlacingIED();
    private updateDraggingIedVisual;
    private updateDraggingLabelVisual;
    private clearDraggingState;
    onWheelZoom(evt: WheelEvent): void;
    clearFilter(): void;
    activeFilter(): boolean;
    filterCbName(conn: Connection): boolean;
    filterSourceIED(conn: Connection): boolean;
    filterTargetIED(conn: Connection): boolean;
    static parseCsvTokens(text: string): string[];
    static matchPriorityToken(prioText: string | null | undefined, token: string): boolean;
    static matchVlanToken(vlanText: string | null | undefined, token: string): boolean;
    static parseVlanRawToNumber(text: string | null | undefined): number | null;
    static parseVlanTokenToNumber(text: string | null | undefined): number | null;
    static canonicalVlanDecimal(text: string | null | undefined): string;
    static parsePriorityRawToNumber(text: string | null | undefined): number | null;
    static parsePriorityTokenToNumber(text: string | null | undefined): number | null;
    static canonicalPriorityDecimal(text: string | null | undefined): string;
    private parseVlanInputToSelected;
    private syncVlanFilterFromSelection;
    private handleVlanTextInput;
    private toggleVlanSelection;
    private parsePriorityInputToSelected;
    private syncPriorityFilterFromSelection;
    private handlePriorityTextInput;
    private togglePrioritySelection;
    filterVlan(conn: Connection): boolean;
    filterPriority(conn: Connection): boolean;
    filterManufacturer(conn: Connection): boolean;
    filterIedType(conn: Connection): boolean;
    filterConnections(conn: Connection): boolean;
    resetIedSelection(): void;
    selectIED(ied: IED): void;
    renderedLabelPosition(element: Element): Point;
    renderLabel(ied: IED): TemplateResult<2>;
    renderedPosition(element: Element): Point;
    renderIED(ied: IED): TemplateResult<2>;
    private computeVlanPriorityValues;
    private computeManufacturerTypeValues;
    private toggleManufacturerSelection;
    private toggleManufacturerAll;
    private recomputeSelectedManufacturers;
    private toggleTypeSelection;
    protected updated(changedProperties: PropertyValues): void;
    firstUpdated(): void;
    private toggleVlanExpanded;
    private togglePriorityExpanded;
    renderFilterBox(): TemplateResult;
    renderFilterFab(): TemplateResult;
    renderService(controlBlock: string): TemplateResult[];
    renderInfoBox(): TemplateResult;
    render(): TemplateResult<1>;
    static styles: import("lit").CSSResult;
}
export {};
