export declare const patterns: {
    string: string;
    normalizedString: string;
    name: string;
    tName: string;
    nmToken: string;
    names: string;
    nmTokens: string;
    decimal: string;
    unsigned: string;
    integer: string;
    alphanumericFirstUpperCase: string;
    alphanumericFirstLowerCase: string;
    alphanumericFirst: string;
    ldInst: string;
    prefix: string;
    lnClass: string;
    lnInst: string;
    abstractDataAttributeName: string;
    cdc: string;
    uuid: string;
    id: string;
    path: string;
    mappedDoName: string;
    vlanid: string;
    vlanPriority: string;
    ipv4: string;
    ipv6: string;
};
export declare const maxLength: {
    cbName: number;
    abstracDaName: number;
    ldInst: number;
    prefix: number;
    lnInst: number;
    dosName: number;
};
export declare const predefinedBasicTypeEnum: string[];
export declare const valKindEnum: string[];
export declare const functionalConstraintEnum: string[];
export declare const attributeNameEnum: string[];
export declare const tSpecServiceType: string[];
export declare const tSCLFileType: string[];
export declare const tRightEnum: string[];
export declare const tSmpMod: string[];
